version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - /Users/shawnpatel/WeightVisual/WeightVisual/backend:/weightVisual/backend
      - /weightVisual/backend/node_modules
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - /Users/shawnpatel/WeightVisual/WeightVisual/frontend:/weightVisual/frontend
      - /weightVisual/frontend/node_modules

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
